// <auto-generated />
using System.Text.Json;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Ordis.Migrations
{
    [DbContext(typeof(OrdisContext))]
    partial class OrdisContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PlayerCharacter", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int?>("Mana")
                        .HasColumnType("integer")
                        .HasColumnName("mana");

                    b.Property<string>("ManaReadoutChannelId")
                        .HasColumnType("text")
                        .HasColumnName("mana_readout_channel_id");

                    b.Property<string>("ManaReadoutMessageId")
                        .HasColumnType("text")
                        .HasColumnName("mana_readout_message_id");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("RollServerId")
                        .HasColumnType("text")
                        .HasColumnName("roll_server_id");

                    b.Property<string>("SavedRolls")
                        .HasColumnType("text")
                        .HasColumnName("saved_rolls");

                    b.Property<string>("SpellBlock")
                        .HasColumnType("text")
                        .HasColumnName("spell_block");

                    b.Property<string>("SpellBlockChannelId")
                        .HasColumnType("text")
                        .HasColumnName("spell_block_channel_id");

                    b.Property<string>("SpellBlockHash")
                        .HasColumnType("text")
                        .HasColumnName("spell_block_hash");

                    b.Property<string>("SpellBlockMessageId")
                        .HasColumnType("text")
                        .HasColumnName("spell_block_message_id");

                    b.Property<JsonDocument>("StatBlock")
                        .HasColumnType("jsonb")
                        .HasColumnName("stat_block");

                    b.Property<string>("StatBlockChannelId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_channel_id");

                    b.Property<string>("StatBlockHash")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_hash");

                    b.Property<string>("StatBlockMessageId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_message_id");

                    b.Property<string>("StatBlockServerId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_server_id");

                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("new_characters_pkey");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Server", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("DefaultRollChannel")
                        .HasColumnType("text")
                        .HasColumnName("default_roll_channel");

                    b.Property<string>("DefaultRollServer")
                        .HasColumnType("text")
                        .HasColumnName("default_roll_server");

                    b.HasKey("Id")
                        .HasName("servers_pkey");

                    b.ToTable("servers", (string)null);
                });

            modelBuilder.Entity("User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int?>("Count")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("count");

                    b.Property<int?>("SelectedCharacter")
                        .HasColumnType("integer")
                        .HasColumnName("selected_character");

                    b.Property<string>("SelectedCharacterId")
                        .HasColumnType("text")
                        .HasColumnName("selected_character_id");

                    b.Property<string>("StatBlock")
                        .HasColumnType("text")
                        .HasColumnName("stat_block");

                    b.Property<string>("StatBlockChannelId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_channel_id");

                    b.Property<string>("StatBlockHash")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_hash");

                    b.Property<string>("StatBlockMessageId")
                        .HasColumnType("text")
                        .HasColumnName("stat_block_message_id");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("users_pkey");

                    b.ToTable("users", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
